### ISSUE TITLE
Game page issues

### ISSUE THREAD

**Issue by pankajan05** [Adventure-Club-mob/Website#41]
![image](https://user-images.githubusercontent.com/37388848/140872896-21ac5101-7bfa-4684-ae84-2766aa8fb623.png)

1. The description needs to add. Currently, there is no good description. Please update the description correctly.
2. The game played, like, comments didn't work. please update those.

**Comment by imvinojanv** [comment]
Yep.. I can put the description there. but the Content creating team wants to give the description content to that. after I'll update

**Comment by pankajan05** [comment]
Just search the game name and get the description don't wait until they give the content.
